### PR TITLE
MDEV-23176: freebsd build failure fix

### PR DESCRIPTION
**Pull request by grooverdan**

### CODE REVIEW

**Comment by LinuxJedi** [comment]
Good fix, many thanks!

**Comment by grooverdan** [comment]
Thanks for the merge.

**Comment by xenu** [comment]
Yeah, @brad0 is right. It isn't specific to FreeBSD, [the POSIX specification](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/netinet_in.h.html) says that `sockaddr_in` must be defined inside `netinet/in.h`.

I found this ticket because this issue causes a build error on DragonFly BSD.

**Comment by grooverdan** [comment]
@xenu thanks for providing a substantial reference. Please submit a PR.

**Comment by xenu** [comment]
Done (#89)

**Pull request merged**
